### ISSUE TITLE
"Location Outside Grid" Warning

### ISSUE THREAD

**Issue by ztlawton** [JamesBremner/workshoplocator#13] opened 2023-04-19 15:02 UTC
Example 1:

```
E:\Users\Zachary\Documents\GitHub\workshoplocator\bin>workshopLocator.exe
Input Workshop Mix
Enter number of each workshop type in order
Agriculture Biotech Electronics Energy HeavyIndustry
2 5 3 2 0

Layout
Agriculture Chambers (Workshop): location: 2 4 temp: 40 productivity: 52
        Greenhouse (Module): location: 1 4
        Greenhouse (Module): location: 3 4
        Solar Cells (Module): location: 2 5
        Artificial-G Lab (Module): location: 2 3
Agriculture Chambers (Workshop): location: 4 4 temp: 40 productivity: 40
        Artificial-G Lab (Module): location: 2 3
        Greenhouse (Module): location: 5 4
        Solar Cells (Module): location: 4 5
        Artificial-G Lab (Module): location: 4 3
Biotech Complex (Workshop): location: 2 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 1 7
        Solar Cells (Module): location: 3 7
        Greenhouse (Module): location: 2 8
Biotech Complex (Workshop): location: 5 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 4 7
        Solar Cells (Module): location: 6 7
        Greenhouse (Module): location: 5 8
Biotech Complex (Workshop): location: 8 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 7 7
        Solar Cells (Module): location: 9 7
        Greenhouse (Module): location: 8 8
Biotech Complex (Workshop): location: 11 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 10 7
        Solar Cells (Module): location: 12 7
        Greenhouse (Module): location: 11 8
Biotech Complex (Workshop): location: 14 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 13 7
        Solar Cells (Module): location: 15 7
        Greenhouse (Module): location: 14 8
Electronics Cleanroom (Workshop): location: 2 13 temp: 29 productivity: 45
        Solar Cells (Module): location: 1 13
        Stowage Platform (Module): location: 3 13
        Recycling System (Module): location: 2 14
Electronics Cleanroom (Workshop): location: 5 13 temp: 29 productivity: 45
        Solar Cells (Module): location: 4 13
        Stowage Platform (Module): location: 6 13
        Recycling System (Module): location: 5 14
Electronics Cleanroom (Workshop): location: 8 13 temp: 29 productivity: 45
        Solar Cells (Module): location: 7 13
        Stowage Platform (Module): location: 9 13
        Recycling System (Module): location: 8 14
Energy Cluster (Workshop): location: 2 16 temp: 52 productivity: 34
        Artificial-G Lab (Module): location: 1 16
        Solar Cells (Module): location: 3 16
        Stowage Platform (Module): location: 2 17
Energy Cluster (Workshop): location: 5 16 temp: 52 productivity: 34
        Artificial-G Lab (Module): location: 4 16
        Solar Cells (Module): location: 6 16
        Stowage Platform (Module): location: 5 17

Total Productivity: 520
WARNING: location outside grid
WARNING: location outside grid
    ..........
   ............
  ..............
 .m.m............
.mWmWm...........
..m.m............
.................
.mWmmWmmWmmWmmWm.
..m..m..m..m..m..
.................
.................
.................
.................
.mWmmWmmWm.......
 .m..m..m........
  ..............
 mWmmWm........
```

Example 2:

```
E:\Users\Zachary\Documents\GitHub\workshoplocator\bin>workshopLocator.exe
Input Workshop Mix
Enter number of each workshop type in order
Agriculture Biotech Electronics Energy HeavyIndustry
2 5 3 0 2

Layout
Agriculture Chambers (Workshop): location: 2 4 temp: 40 productivity: 52
        Greenhouse (Module): location: 1 4
        Greenhouse (Module): location: 3 4
        Solar Cells (Module): location: 2 5
        Artificial-G Lab (Module): location: 2 3
Agriculture Chambers (Workshop): location: 4 4 temp: 40 productivity: 40
        Artificial-G Lab (Module): location: 2 3
        Greenhouse (Module): location: 5 4
        Solar Cells (Module): location: 4 5
        Artificial-G Lab (Module): location: 4 3
Biotech Complex (Workshop): location: 2 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 1 7
        Solar Cells (Module): location: 3 7
        Greenhouse (Module): location: 2 8
Biotech Complex (Workshop): location: 5 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 4 7
        Solar Cells (Module): location: 6 7
        Greenhouse (Module): location: 5 8
Biotech Complex (Workshop): location: 8 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 7 7
        Solar Cells (Module): location: 9 7
        Greenhouse (Module): location: 8 8
Biotech Complex (Workshop): location: 11 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 10 7
        Solar Cells (Module): location: 12 7
        Greenhouse (Module): location: 11 8
Biotech Complex (Workshop): location: 14 7 temp: 23 productivity: 45
        Artificial-G Lab (Module): location: 13 7
        Solar Cells (Module): location: 15 7
        Greenhouse (Module): location: 14 8
Electronics Cleanroom (Workshop): location: 2 13 temp: 29 productivity: 45
        Solar Cells (Module): location: 1 13
        Stowage Platform (Module): location: 3 13
        Recycling System (Module): location: 2 14
Electronics Cleanroom (Workshop): location: 5 13 temp: 29 productivity: 45
        Solar Cells (Module): location: 4 13
        Stowage Platform (Module): location: 6 13
        Recycling System (Module): location: 5 14
Electronics Cleanroom (Workshop): location: 8 13 temp: 29 productivity: 45
        Solar Cells (Module): location: 7 13
        Stowage Platform (Module): location: 9 13
        Recycling System (Module): location: 8 14
Heavy Industry Hall (Workshop): location: 5 18 temp: 54 productivity: 45
        Solar Cells (Module): location: 4 18
        Stowage Platform (Module): location: 6 18
        Recycling System (Module): location: 5 19
Heavy Industry Hall (Workshop): location: 8 18 temp: 54 productivity: 45
        Solar Cells (Module): location: 7 18
        Stowage Platform (Module): location: 9 18
        Recycling System (Module): location: 8 19

Total Productivity: 542
WARNING: location outside grid
WARNING: location outside grid
WARNING: location outside grid
WARNING: location outside grid
WARNING: location outside grid
WARNING: location outside grid
WARNING: location outside grid
WARNING: location outside grid
    ..........
   ............
  ..............
 .m.m............
.mWmWm...........
..m.m............
.................
.mWmmWmmWmmWmmWm.
..m..m..m..m..m..
.................
.................
.................
.................
.mWmmWmmWm.......
 .m..m..m........
  ..............
   ............
```

**Comment by JamesBremner** [comment] 2023-04-19 15:35
If you want me to look at an issue you create you should assign it to me.

**Comment by JamesBremner** [comment] 2023-04-19 17:40
Why have you assigned this to me?  Did you test this and find a problem?

**Comment by ztlawton** [comment] 2023-04-19 18:49
Oh, I didn't see that you had committed a change. Sorry.

**Comment by JamesBremner** [comment] 2023-04-19 19:04
Always check the issue thread for recent updates

![image](https://user-images.githubusercontent.com/2046227/233174838-92308258-f8eb-4dc1-ac1c-0143c2a8cb06.png)

**Comment by ztlawton** [comment] 2023-04-21 16:48
Now the two examples I gave for this issue crash with this error message:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cLayout::moduleCount module count exceeded with 53
```

**Comment by JamesBremner** [comment] 2023-04-21 16:58
This is intended behaviour.  You have exceeded the module limit of 48.

**Comment by ztlawton** [comment] 2023-04-21 21:32
If that is intended behavior, should I close this issue?

**Comment by JamesBremner** [comment] 2023-04-21 21:50
Your specified a maximum module limit of 48, so that is what I coded.  If you want to change this, then you should close this issue and create a new enhancement issue.

This is called feature creep and should be avoided.

**Comment by ztlawton** [comment] 2023-04-22 01:19
A layout with the specific Workshop mix "2 5 3 0 2" is possible within the un-modded limit of 48:

https://i.stack.imgur.com/0iPyZ.jpg

**Comment by JamesBremner** [comment] 2023-04-22 14:46
I have no idea how to interpret that image.

What has your comment got to do with this issue?

This issue is about the "outside grid warning" generated by the mix 2 5 3 2 0.  Please test and if you no longer get the warning with this layout then close.

The rule is: one issue per issue.  Otherwise things descend into chaos and nothing gets done.  If you want to change the layout of one or more workshops, please open an issue for that

**Closed** 2023-04-22 16:24 UTC
Labels: bug, test
