### ISSUE TITLE
Up to 5 Energy workshops layout

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/workshoplocator#17] opened 2023-04-19 20:16 UTC
You can stack them like this:

```
art   rad   sol
 │     │     │ 
 ├─────┼────ENR───sol   rad   art
 │     │     │     │     │     │
sto   rad   sol───ENR────┼─────┤
 │     │     │     │     │     │
 ├─────┼────ENR───sol   rad   sto
 │     │     │     │     │     │
art   rad   sol───ENR────┼─────┤
                   │     │     │
                  sol   rad   art
```

**Comment by JamesBremner** [comment] 2023-04-20 19:57
```
Input Workshop Mix
Enter number of each workshop type in order
Agriculture Biotech Electronics Energy HeavyIndustry
0 0 0 3 0

Layout
Energy Cluster (Workshop): location: 4 2 temp: 28 productivity: 80
        Artificial-G Lab (Module): location: 2 1
        Stowage Platform (Module): location: 2 3
        Radiator (Module): location: 3 1
        Radiator (Module): location: 3 3
        Solar Cells (Module): location: 4 1
        Solar Cells (Module): location: 4 3
        Solar Cells (Module): location: 5 2
Energy Cluster (Workshop): location: 5 3 temp: 28 productivity: 80
        Solar Cells (Module): location: 5 2
        Solar Cells (Module): location: 4 3
        Solar Cells (Module): location: 5 4
        Radiator (Module): location: 6 2
        Radiator (Module): location: 6 4
        Artificial-G Lab (Module): location: 7 2
        Stowage Platform (Module): location: 7 4
Energy Cluster (Workshop): location: 4 4 temp: 28 productivity: 80
        Stowage Platform (Module): location: 2 3
        Radiator (Module): location: 3 3
        Solar Cells (Module): location: 4 3
        Solar Cells (Module): location: 5 4
        Artificial-G Lab (Module): location: 2 5
        Radiator (Module): location: 3 5
        Solar Cells (Module): location: 4 5

Module Count: 15 ( max 48 )
0 0 0 3 0  => Total Productivity: 240
    ..........
  mmm..........
  ..Wmmm........
 .mmmW...........
....Wmmm.........
..mmm............
.................
.................
........X........
.................
```

**Comment by ztlawton** [comment] 2023-04-21 16:55
Seems to work for 1, 2, or 3 Energy Workshops are specified, but crashes when more than 3 Energy Workshops are specified:
```
E:\Users\Zachary\Documents\GitHub\workshoplocator\bin>workshopLocator
Input Workshop Mix
Enter number of each workshop type in order
Agriculture Biotech Electronics Energy HeavyIndustry
0 0 0 4 0
terminate called after throwing an instance of 'std::runtime_error'
  what():  cLayout::energy2 max energy workshops ( 3 ) exceeded
```

**Comment by JamesBremner** [comment] 2023-04-21 17:00
Intended behavior

**Comment by ztlawton** [comment] 2023-04-21 21:33
If that is intended behavior, should I close this issue?

**Comment by JamesBremner** [comment] 2023-04-21 21:52
It is your call.  

You specified 4 energy workshops, but I coded just 3 so you could test the layout.  If you want more than 3, let me know.

**Comment by ztlawton** [comment] 2023-04-21 22:26
I'd like the code to allow for up to 5 Energy Workshops.

**Comment by JamesBremner** [comment] 2023-04-23 15:18
```
Input Workshop Mix
Enter number of each workshop type in order
Agriculture Biotech Electronics Energy HeavyIndustry
0 0 0 5 0

Layout
Energy Cluster (Workshop): location: 4 2 temp: 28 productivity: 80
        Artificial-G Lab (Module): location: 2 1
        Stowage Platform (Module): location: 2 3
        Radiator (Module): location: 3 1
        Radiator (Module): location: 3 3
        Solar Cells (Module): location: 4 1
        Solar Cells (Module): location: 4 3
        Solar Cells (Module): location: 5 2
Energy Cluster (Workshop): location: 5 3 temp: 28 productivity: 80
        Solar Cells (Module): location: 5 2
        Solar Cells (Module): location: 4 3
        Solar Cells (Module): location: 5 4
        Radiator (Module): location: 6 2
        Artificial-G Lab (Module): location: 7 2
        Radiator (Module): location: 6 4
        Stowage Platform (Module): location: 7 4
Energy Cluster (Workshop): location: 4 4 temp: 28 productivity: 80
        Solar Cells (Module): location: 4 3
        Solar Cells (Module): location: 5 4
        Solar Cells (Module): location: 4 5
        Stowage Platform (Module): location: 2 3
        Radiator (Module): location: 3 3
        Artificial-G Lab (Module): location: 2 5
        Radiator (Module): location: 3 5
Energy Cluster (Workshop): location: 5 5 temp: 28 productivity: 80
        Solar Cells (Module): location: 5 4
        Solar Cells (Module): location: 4 5
        Solar Cells (Module): location: 5 6
        Radiator (Module): location: 6 4
        Stowage Platform (Module): location: 7 4
        Radiator (Module): location: 6 6
        Artificial-G Lab (Module): location: 7 6
Energy Cluster (Workshop): location: 4 6 temp: 28 productivity: 80
        Artificial-G Lab (Module): location: 2 5
        Stowage Platform (Module): location: 2 7
        Radiator (Module): location: 3 5
        Radiator (Module): location: 3 7
        Solar Cells (Module): location: 4 5
        Solar Cells (Module): location: 4 7
        Solar Cells (Module): location: 5 6

Module Count: 21 ( max 48 )
0 0 0 5 0  => Total Productivity: 400
    ..........
  ars..........
  ..Nsra........
 .trsN...........
....Nsrt.........
..arsN...........
....Nsra.........
..trs............
........X........
.................
.................
.................
.................
.................
 ................
  ..............
   ............
```

**Comment by JamesBremner** [comment] 2023-04-23 15:34
v1.0.1 released

**Comment by ztlawton** [comment] 2023-04-30 15:15
Looks good!

**Closed by ztlawton** 2023-04-30 15:15 UTC
Labels: enhancement, test
